### ISSUE TITLE
The sample doesn't work.

### ISSUE THREAD

**Issue by starikcetin** [omid3098/OpenWatcher#1]
At `Watcher.cs` line 46, the count of `fieldObjects` always evaluates to 0, thus the code doesn't draw anything.

**Comment by omid3098** [comment]
just downloaded a clean repository and checked that, sample scene works fine here (unity 2017.2.0f3). 
what version of unity are you using?
would you please re-check using a clean version of this repository?

**Comment by starikcetin** [comment]
I was putting the OpenWatcher folder in the Plugins folder, which was causing it to be put in the first pass assembly, thus it was not able to access the MonoBehaviours in the Assets folder. Moving the OpenWatcher folder out of Plugins folder fixed the problem.

Therefore the plugin itself doesn't have an issue, but you might want to add a reminder about this in the Readme file.
